language: scala
scala:
- 2.10.4
jdk:
- openjdk7
after_success:
- sbt publishMasterOnTravis
cache:
  directories:
  - $HOME/.ivy2/cache
env:
  global:
  - FOO=bar
  - secure: NKCYnxbH6dq8qTq5bzM/eIU1LFDxNSzD6VN0OGhynaxF3Q5JaawEv3Av0tPHR9R/o2i9t8QtWPzYBfwXtwcdaantjAa15PdK9/JDqv0ON1cMhZcKbOkNueEkNa8ehJ/JMBB+55f+G4y2XqykIur3d9TJ3z91PG866hQJRaZ55es=
before_script:
- env
- sbt "show credentials"
